version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - PROFILE=${PROFILE:-dev}
      - STRIPE_KEY=${STRIPE_KEY}
      - DATASOURCE_URL=${DATASOURCE_URL:-jdbc:postgresql://postgres:5432/emporium}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME:-admin}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD:-admin}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin}
      - STRIPE_KEY=${STRIPE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_SECRET}
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin}
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-auth}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
